# Generated by Django 5.0.2 on 2024-04-29 19:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_footerlinkgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinkgroup',
            options={},
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('link_group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to='snippets.footerlinkgroup')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
