# Generated by Django 5.0.2 on 2024-04-29 20:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_footerlinkgroup_options_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link_group',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='snippets.footerlinkgroup'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_title',
            field=models.CharField(help_text='add name of the link', max_length=255),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.URLField(help_text='add url for the link', null=True),
        ),
        migrations.AlterField(
            model_name='footerlinkgroup',
            name='title',
            field=models.CharField(help_text='Add a title for this group of links', max_length=200),
        ),
    ]
