# Generated by Django 5.0.2 on 2024-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_remove_footer_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinkgroup',
            options={'ordering': ['sort_order']},
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
