# Generated by Django 5.0.2 on 2024-04-29 22:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_footerlinkgroup_options_delete_footerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinkgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='footerlinkgroup',
            name='sort_order',
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(help_text='add name of the link', max_length=255)),
                ('url', models.URLField(help_text='add url for the link', null=True)),
                ('link_group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='snippets.footerlinkgroup')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
