# Generated by Django 5.0.2 on 2024-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_footerlinkgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkgroup',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
