# Generated by Django 5.0.2 on 2024-04-30 00:04

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_remove_footerlink_url_footerlink_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='page_link',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_content',
            field=wagtail.fields.StreamField([('page_chooser', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='Select a page'))]))], blank=True, null=True),
        ),
    ]
