# Generated by Django 5.0.2 on 2024-04-30 00:30

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_alter_footerlink_link_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link_content',
            field=wagtail.fields.StreamField([('link_content', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='Choose an internal page.', label='Internal Page', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Enter the external URL.', label='External URL', required=False))]))], blank=True, null=True),
        ),
    ]
