# Generated by Django 5.0.2 on 2024-04-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_alter_footerlink_link_content'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='link_content',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='external_url',
            field=models.URLField(blank=True, help_text='insert an external url', null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
