# Generated by Django 5.0.2 on 2024-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0019_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='name',
            field=models.CharField(default='main header', max_length=255),
            preserve_default=False,
        ),
    ]
