# Generated by Django 5.0.2 on 2024-04-30 06:24

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0023_alter_navitem_nav_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='nav_content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock()), ('menu_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_title', wagtail.blocks.CharBlock()), ('page_link', wagtail.blocks.CharBlock()), ('external_url', wagtail.blocks.CharBlock())])))]))]),
        ),
    ]
