# Generated by Django 5.0.2 on 2024-05-01 01:34

import streams.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0025_alter_navitem_nav_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='nav_content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock()), ('menu_links', wagtail.blocks.ListBlock(streams.blocks.LinkBlock))]))]),
        ),
    ]
