# Generated by Django 5.0.2 on 2024-05-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0026_alter_navitem_nav_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navitem',
            old_name='nav_content',
            new_name='dropdown_nav_content',
        ),
    ]
