# Generated by Django 5.0.2 on 2024-05-01 02:44

import streams.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0029_alter_navitem_dropdown_nav_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='nav_title',
        ),
        migrations.AddField(
            model_name='navitem',
            name='nav_item_title',
            field=models.CharField(default=1, help_text='Name of the top navbar menu item. (e.g. About Us)', max_length=255, verbose_name='Navbar Item Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navitem',
            name='dropdown_nav_content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock()), ('menu_links', wagtail.blocks.ListBlock(streams.blocks.LinkBlock))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='nav_subtitle',
            field=models.CharField(blank=True, help_text='add a short sentence that expands on the title (e.g. discover what we are about)', max_length=255, null=True, verbose_name='Navbar Item Subtitle'),
        ),
    ]
