# Generated by Django 5.0.2 on 2024-05-01 03:28

import django.db.models.deletion
import modelcluster.fields
import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0032_rename_dropdown_nav_content_navitem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItemOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nav_item_title', models.CharField(help_text='Name of the top navbar menu item. (e.g. About Us)', max_length=255, verbose_name='Title')),
                ('nav_subtitle', models.CharField(blank=True, help_text='add a short sentence that expands on the title (e.g. discover what we are about)', max_length=255, null=True, verbose_name='Subtitle')),
                ('content', wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The text the user sees on the link', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))])), ('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(help_text='The text the user sees on the link', max_length=150, required=True)), ('destination', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The destination page when this link is clicked', max_length=150)), ('external_url', wagtail.blocks.URLBlock(help_text='An external destination when this link is clicked', max_length=150))], help_text='Choose either a page or an external URL as the destination.', max_num=1, required=False))]))], blank=True, help_text='Build the dropdown menu', null=True)),
                ('header', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='snippets.header')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
