# Generated by Django 5.0.2 on 2024-05-06 04:17

import streams.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0036_alter_navitemorderable_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitemorderable',
            name='content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(streams.blocks.LinkBlock))])), ('nested_list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='Top level menu title', max_length=150, required=True)), ('sub_menus', wagtail.blocks.ListBlock(streams.blocks.ListMenuBlock))])), ('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(help_text='The text the user sees on the link', max_length=150, required=True)), ('destination', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The destination page when this link is clicked', max_length=150, required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='An external destination when this link is clicked', max_length=150, required=False))], help_text='Choose either a page or an external URL as the destination.', max_num=1, required=False))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
    ]
