# Generated by Django 5.0.2 on 2024-05-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0037_alter_navitemorderable_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='text',
            new_name='title',
        ),
    ]
