# Generated by Django 5.0.2 on 2024-05-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0038_rename_text_footer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='navitemorderable',
            old_name='content',
            new_name='navitem_content',
        ),
        migrations.RenameField(
            model_name='navitemorderable',
            old_name='nav_subtitle',
            new_name='navitem_subtitle',
        ),
        migrations.RenameField(
            model_name='navitemorderable',
            old_name='nav_item_title',
            new_name='navitem_title',
        ),
        migrations.RenameField(
            model_name='navitemorderable',
            old_name='header',
            new_name='parent',
        ),
    ]
