# Generated by Django 5.0.2 on 2024-05-31 01:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0039_rename_name_header_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlinkgroup',
            name='snippet',
        ),
        migrations.CreateModel(
            name='LinkGroupOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('linkgroup_title', models.CharField(help_text='Add link group title', max_length=200)),
                ('linkgroup_content', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(help_text='The text the user sees on the link', max_length=150, required=True)), ('destination', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The destination page when this link is clicked', max_length=150, required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='An external destination when this link is clicked', max_length=150, required=False))], help_text='Choose either a page or an external URL as the destination.', max_num=1, required=False))]))], blank=True, help_text='Add links to the group', null=True)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to='snippets.footer')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='FooterLinkGroup',
        ),
    ]
