# Generated by Django 5.0.2 on 2024-05-31 15:29

import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0042_rename_linkgroup_title_linkgrouporderable_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgrouporderable',
            name='content',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('link_title', wagtail.blocks.CharBlock(help_text='name of the link', max_length=150, required=True)), ('external_url', wagtail.blocks.URLBlock(help_text='An external destination when this link is clicked', required=False))]))], blank=True, help_text='Add links (i.e. links under this group)', null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='navitemorderable',
            name='content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))])), ('nested_list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='Top level menu title', max_length=150, required=True)), ('sub_menus', wagtail.blocks.ListBlock(blocks.blocks.MenuBlock))])), ('link', wagtail.blocks.StructBlock([('link_title', wagtail.blocks.CharBlock(help_text='name of the link', max_length=150, required=True)), ('external_url', wagtail.blocks.URLBlock(help_text='An external destination when this link is clicked', required=False))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
    ]
