# Generated by Django 5.0.2 on 2024-06-01 15:29

import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0044_rename_content_linkgrouporderable_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitemorderable',
            name='content',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))])), ('nested_list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='Top level menu title', max_length=150, required=True)), ('sub_menus', wagtail.blocks.ListBlock(blocks.blocks.MenuBlock))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
    ]
