# Generated by Django 5.0.2 on 2024-06-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0045_alter_navitemorderable_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navitemorderable',
            old_name='content',
            new_name='menus',
        ),
    ]
