# Generated by Django 5.0.2 on 2024-06-01 23:49

import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0046_rename_content_navitemorderable_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitemorderable',
            name='menus',
            field=wagtail.fields.StreamField([('list_menu', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
    ]
