# Generated by Django 5.0.2 on 2024-06-02 12:51

import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0057_alter_linkgrouporderable_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkgrouporderable',
            name='title',
        ),
        migrations.AlterField(
            model_name='linkgrouporderable',
            name='links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
    ]
