# Generated by Django 5.0.2 on 2024-06-02 12:59

import blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0058_remove_linkgrouporderable_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='link_groups',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.StructBlock([('menu_title', wagtail.blocks.CharBlock(help_text='The menu title', max_length=150, required=True)), ('links', wagtail.blocks.ListBlock(blocks.blocks.LinkBlock))]))], blank=True, help_text='Build the dropdown menu', null=True),
        ),
        migrations.DeleteModel(
            name='LinkGroupOrderable',
        ),
    ]
