# Generated by Django 5.0.2 on 2024-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_paragraph_homepage_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(null=True),
        ),
    ]
