services:

  nginx:
    container_name: sinuweb-nginx
    image: nginx:1.25.5
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend-static:/staticfiles
      - backend-media:/mediafiles
    depends_on:
      - frontend

  frontend:
    container_name: sinuweb-frontend
    image: sinuweb/nextjsfrontend:dev
    build:
      context: ./sinuweb-frontend
      dockerfile: .docker/dev/Dockerfile
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true # for windows users - Sol from @Kobe E
    volumes:
      - ./sinuweb-frontend:/src
      - /src/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    container_name: sinuweb-backend
    image: sinuweb/wagtailbackend:dev
    build:
      context: ./sinuweb_hdl_cms
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - backend-static:/staticfiles
      - backend-media:/mediafiles
      - ./sinuweb_hdl_cms:/app
    command: >
      sh -c "
      set -xe;
      python manage.py migrate --noinput;
      python manage.py runserver 0.0.0.0:80
      "
    depends_on:
      - db

  db:
    container_name: sinuweb-db
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  backend-static:
  backend-media:
  db-data: