services:

  nginx:
    container_name: sinuweb-nginx
    image: nginx:1.25.5
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend-static:/staticfiles
      - backend-media:/mediafiles
    depends_on:
      - frontend

  frontend:
    container_name: sinuweb-frontend
    image: sinuweb/nextjsfrontend:prod
    build:
      context: ./sinuweb-frontend
      dockerfile: .docker/prod/Dockerfile
    command: ["node", "server.js"]
    depends_on:
      - backend

  backend:
    container_name: sinuweb-backend
    image: sinuweb/wagtailbackend:prod
    build:
      context: ./sinuweb_hdl_cms
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=False
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    volumes:
      - backend-static:/staticfiles
      - backend-media:/mediafiles
    command: >
      sh -c "
      set -xe;
      python manage.py migrate --noinput;
      gunicorn --bind 0.0.0.0:8000 sinuweb_hdl_cms.wsgi:application
      "
    depends_on:
      - db

  db:
    container_name: sinuweb-db
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  backend-static:
  backend-media:
  db-data: