# Generated by Django 5.0.2 on 2024-04-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPage',
            new_name='NewsDetailPage',
        ),
        migrations.RenameModel(
            old_name='NewsIndexPage',
            new_name='NewsListingPage',
        ),
    ]
