# Generated by Django 5.0.2 on 2024-04-26 04:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_newspage_newsdetailpage_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetailpage',
            name='news_title',
        ),
        migrations.RemoveField(
            model_name='newslistingpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='custom_title',
            field=models.CharField(default=1, help_text='overwrites default title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='news_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='newslistingpage',
            name='custom_title',
            field=models.CharField(default=1, help_text='overwrites default title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
    ]
