# Generated by Django 5.0.2 on 2024-04-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsdetailpage_news_title_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsListingPage',
            new_name='NewsIndexPage',
        ),
        migrations.RenameModel(
            old_name='NewsDetailPage',
            new_name='NewsPage',
        ),
    ]
