# Generated by Django 5.0.2 on 2024-05-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_newslistingpage_newsindexpage_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPage',
            new_name='NewsPostPage',
        ),
    ]
