const DUMMY_NEWS = [
    {
        id: 1,
        title: "SINU hosts historical symposium for PM candidates on the eve of PM's election",
        short: `Today, Solomon Islands National University (SINU) hosted a significant symposium, allowing one of the Prime Ministerial candidates for the 12th parliament to articulate his leadership visions and policies.`,
        date: `3 Feb, 2024`,
        type: 'press release',
        slug: "sinu-hosts-historical-symposium-for-pm-candidate-on-the-eve-of-pms-election",
        body: `<p className=" text-slate-700 leading-relaxed tracking-wider">
        A research team has developed a world-first platform to define the impact of exposure to landscape fire smoke on the heart and lungs.
        <br />
    
    The University of Newcastle and HMRI team, led by Professor Jay Horvat and Dr Henry Gomez, found short and long-term exposure to landscape fire smoke particulate matter (bushfire smoke) increased the hyperresponsiveness of airways and induced steroid-insensitivity in experimental asthma.
    
    They also found that short-term exposure to bushfire smoke decreased cardiac function and this was associated with the expression of gene changes relating to oxidative stress and cardiovascular pathologies.
    
    The research, driven by the events of the 2019 and 2020 ‘Black Summer’ bushfires, was funded by a Medical Research Future Fund grant.
    
    Professor Horvat said millions of people in Australia were exposed to unprecedented levels of particulate matter from landscape fires during the ‘Black Summer’ bushfires.
    
    “This was associated with large increases in people having respiratory and cardiovascular symptoms. People with asthma experienced worsened disease symptoms and had an increased needed to seek medical help as a result of exposure to particulate matter generated by the fires. Furthermore, the number heart attacks almost doubled in regional locations during the 2019/2020 Black Summer period.”
    
    The findings, published in The Journal of Allergy and Clinical Immunology, describe a world-first platform for understanding how landscape fire exposure affects heart and lung physiology. The research will be used to help identify therapies to protect people from the harmful effects of exposure.
    
    “Our research demonstrates that even small amounts of physiologically-relevant particular matter from landscape fire smoke has significant effects on lung and heart physiology, worsening key features of asthma and preventing mainstay suppressant medications from having much of an effect on symptoms,” says Professor Horvat.
    
    “What our experience showed us during the Black Summer bushfires is that completely avoiding exposure to landscape fire particulate matter inhalation is almost impossible. Our research shows that exposure to even low amounts of landscape fire particulate matter over a short period of time has a significant effect on heart and lung function.
    
    “Therefore, new therapeutic strategies are required to protect people from the harmful effects of exposure, particularly for those that are at increased risk, such as those with asthma or cardiovascular disease. Better strategies for treating and preventing the harmful effects of landscape fire smoke exposure are going to become more important given that the prevalence and intensity of landscape fires is likely to increase globally as a result of climate change.
    
    “Our findings show that particulate matter generated from different fuel sources have very similar effects at the same level of exposure. However, more research is required to determine how different levels of particulate matter generated from different fuel sources in different geographical regions and countries affect different populations of people, especially those with underlying respiratory and cardiovascular conditions.
    
    “Whilst our findings show that targeting airway smooth muscle contraction or oxidative stress pathways may provide novel strategies for the protecting against the effects of landscape fire inhalation on respiratory and cardiovascular disease, more studies are required to identify appropriate therapies” says Professor Horvat.
    
    The research was conducted in collaboration with the Asthma and Breathing research program led by Professor Peter Gibson and Professor Vanessa McDonald, and National Heart Foundation Future Leader Fellow from the HMRI Heart and Stroke program, Professor Doan Ngo.
        </p>`
    },
    {
        id: 2,
        title: "SINU Rugby hosts fundraising dinner to support teams",
        short: `SINU Rugby hosted a fundraising dinner this evening Friday, April 12, 2024, at Lokol Fusion Café & Bar in support of the SINU Men’s and Women’s rugby teams. `,
        date: `3 Feb, 2024`,
        type: 'press release',
        slug: "sinu-rugby-hosts-fundraising-dinner-to-support-teams",
        body: `<p className=" text-slate-700 leading-relaxed tracking-wider">
        A research team has developed a world-first platform to define the impact of exposure to landscape fire smoke on the heart and lungs.
        <br />
    
    The University of Newcastle and HMRI team, led by Professor Jay Horvat and Dr Henry Gomez, found short and long-term exposure to landscape fire smoke particulate matter (bushfire smoke) increased the hyperresponsiveness of airways and induced steroid-insensitivity in experimental asthma.
    
    They also found that short-term exposure to bushfire smoke decreased cardiac function and this was associated with the expression of gene changes relating to oxidative stress and cardiovascular pathologies.
    
    The research, driven by the events of the 2019 and 2020 ‘Black Summer’ bushfires, was funded by a Medical Research Future Fund grant.
    
    Professor Horvat said millions of people in Australia were exposed to unprecedented levels of particulate matter from landscape fires during the ‘Black Summer’ bushfires.
    
    “This was associated with large increases in people having respiratory and cardiovascular symptoms. People with asthma experienced worsened disease symptoms and had an increased needed to seek medical help as a result of exposure to particulate matter generated by the fires. Furthermore, the number heart attacks almost doubled in regional locations during the 2019/2020 Black Summer period.”
    
    The findings, published in The Journal of Allergy and Clinical Immunology, describe a world-first platform for understanding how landscape fire exposure affects heart and lung physiology. The research will be used to help identify therapies to protect people from the harmful effects of exposure.
    
    “Our research demonstrates that even small amounts of physiologically-relevant particular matter from landscape fire smoke has significant effects on lung and heart physiology, worsening key features of asthma and preventing mainstay suppressant medications from having much of an effect on symptoms,” says Professor Horvat.
    
    “What our experience showed us during the Black Summer bushfires is that completely avoiding exposure to landscape fire particulate matter inhalation is almost impossible. Our research shows that exposure to even low amounts of landscape fire particulate matter over a short period of time has a significant effect on heart and lung function.
    
    “Therefore, new therapeutic strategies are required to protect people from the harmful effects of exposure, particularly for those that are at increased risk, such as those with asthma or cardiovascular disease. Better strategies for treating and preventing the harmful effects of landscape fire smoke exposure are going to become more important given that the prevalence and intensity of landscape fires is likely to increase globally as a result of climate change.
    
    “Our findings show that particulate matter generated from different fuel sources have very similar effects at the same level of exposure. However, more research is required to determine how different levels of particulate matter generated from different fuel sources in different geographical regions and countries affect different populations of people, especially those with underlying respiratory and cardiovascular conditions.
    
    “Whilst our findings show that targeting airway smooth muscle contraction or oxidative stress pathways may provide novel strategies for the protecting against the effects of landscape fire inhalation on respiratory and cardiovascular disease, more studies are required to identify appropriate therapies” says Professor Horvat.
    
    The research was conducted in collaboration with the Asthma and Breathing research program led by Professor Peter Gibson and Professor Vanessa McDonald, and National Heart Foundation Future Leader Fellow from the HMRI Heart and Stroke program, Professor Doan Ngo.
        </p>`
    },
    {
        id: 3,
        title: "Proffesor Transform Aqorau,Vice Chancellor of SINU, congratulates Hon. Jeremiah Manele on his election as Prime Minister",
        short: `Solomon Islands National University (SINU) extends its heartfelt congratulations to Honourable Jeremiah Manele on his election as the Prime Minister of the Solomon Islands.`,
        date: `3 Feb, 2024`,
        type: 'press release',
        slug: 'proffesor-transform-aqorau-vice-chancellor-of-sinu-congratulates-hon-jeremiah-manele-on-his-election-as-prime-minister',
        body: `<p className=" text-slate-700 leading-relaxed tracking-wider">
        A research team has developed a world-first platform to define the impact of exposure to landscape fire smoke on the heart and lungs.
        <br />
    
    The University of Newcastle and HMRI team, led by Professor Jay Horvat and Dr Henry Gomez, found short and long-term exposure to landscape fire smoke particulate matter (bushfire smoke) increased the hyperresponsiveness of airways and induced steroid-insensitivity in experimental asthma.
    
    They also found that short-term exposure to bushfire smoke decreased cardiac function and this was associated with the expression of gene changes relating to oxidative stress and cardiovascular pathologies.
    
    The research, driven by the events of the 2019 and 2020 ‘Black Summer’ bushfires, was funded by a Medical Research Future Fund grant.
    
    Professor Horvat said millions of people in Australia were exposed to unprecedented levels of particulate matter from landscape fires during the ‘Black Summer’ bushfires.
    
    “This was associated with large increases in people having respiratory and cardiovascular symptoms. People with asthma experienced worsened disease symptoms and had an increased needed to seek medical help as a result of exposure to particulate matter generated by the fires. Furthermore, the number heart attacks almost doubled in regional locations during the 2019/2020 Black Summer period.”
    
    The findings, published in The Journal of Allergy and Clinical Immunology, describe a world-first platform for understanding how landscape fire exposure affects heart and lung physiology. The research will be used to help identify therapies to protect people from the harmful effects of exposure.
    
    “Our research demonstrates that even small amounts of physiologically-relevant particular matter from landscape fire smoke has significant effects on lung and heart physiology, worsening key features of asthma and preventing mainstay suppressant medications from having much of an effect on symptoms,” says Professor Horvat.
    
    “What our experience showed us during the Black Summer bushfires is that completely avoiding exposure to landscape fire particulate matter inhalation is almost impossible. Our research shows that exposure to even low amounts of landscape fire particulate matter over a short period of time has a significant effect on heart and lung function.
    
    “Therefore, new therapeutic strategies are required to protect people from the harmful effects of exposure, particularly for those that are at increased risk, such as those with asthma or cardiovascular disease. Better strategies for treating and preventing the harmful effects of landscape fire smoke exposure are going to become more important given that the prevalence and intensity of landscape fires is likely to increase globally as a result of climate change.
    
    “Our findings show that particulate matter generated from different fuel sources have very similar effects at the same level of exposure. However, more research is required to determine how different levels of particulate matter generated from different fuel sources in different geographical regions and countries affect different populations of people, especially those with underlying respiratory and cardiovascular conditions.
    
    “Whilst our findings show that targeting airway smooth muscle contraction or oxidative stress pathways may provide novel strategies for the protecting against the effects of landscape fire inhalation on respiratory and cardiovascular disease, more studies are required to identify appropriate therapies” says Professor Horvat.
    
    The research was conducted in collaboration with the Asthma and Breathing research program led by Professor Peter Gibson and Professor Vanessa McDonald, and National Heart Foundation Future Leader Fellow from the HMRI Heart and Stroke program, Professor Doan Ngo.
        </p>`
    },
    {
        id: 4,
        title: "New Studies aims to put asthma into remission",
        short: `Professor Peter Gibson from the HMRI Asthma and Breathing program says the findings were very promising.`,
        date: `3 Feb, 2024`,
        type: 'press release',
        slug: "new-studies-aims-to-put-asthma-into-remission",
        body: `<p className=" text-slate-700 leading-relaxed tracking-wider">
        A research team has developed a world-first platform to define the impact of exposure to landscape fire smoke on the heart and lungs.
        <br />
    
    The University of Newcastle and HMRI team, led by Professor Jay Horvat and Dr Henry Gomez, found short and long-term exposure to landscape fire smoke particulate matter (bushfire smoke) increased the hyperresponsiveness of airways and induced steroid-insensitivity in experimental asthma.
    
    They also found that short-term exposure to bushfire smoke decreased cardiac function and this was associated with the expression of gene changes relating to oxidative stress and cardiovascular pathologies.
    
    The research, driven by the events of the 2019 and 2020 ‘Black Summer’ bushfires, was funded by a Medical Research Future Fund grant.
    
    Professor Horvat said millions of people in Australia were exposed to unprecedented levels of particulate matter from landscape fires during the ‘Black Summer’ bushfires.
    
    “This was associated with large increases in people having respiratory and cardiovascular symptoms. People with asthma experienced worsened disease symptoms and had an increased needed to seek medical help as a result of exposure to particulate matter generated by the fires. Furthermore, the number heart attacks almost doubled in regional locations during the 2019/2020 Black Summer period.”
    
    The findings, published in The Journal of Allergy and Clinical Immunology, describe a world-first platform for understanding how landscape fire exposure affects heart and lung physiology. The research will be used to help identify therapies to protect people from the harmful effects of exposure.
    
    “Our research demonstrates that even small amounts of physiologically-relevant particular matter from landscape fire smoke has significant effects on lung and heart physiology, worsening key features of asthma and preventing mainstay suppressant medications from having much of an effect on symptoms,” says Professor Horvat.
    
    “What our experience showed us during the Black Summer bushfires is that completely avoiding exposure to landscape fire particulate matter inhalation is almost impossible. Our research shows that exposure to even low amounts of landscape fire particulate matter over a short period of time has a significant effect on heart and lung function.
    
    “Therefore, new therapeutic strategies are required to protect people from the harmful effects of exposure, particularly for those that are at increased risk, such as those with asthma or cardiovascular disease. Better strategies for treating and preventing the harmful effects of landscape fire smoke exposure are going to become more important given that the prevalence and intensity of landscape fires is likely to increase globally as a result of climate change.
    
    “Our findings show that particulate matter generated from different fuel sources have very similar effects at the same level of exposure. However, more research is required to determine how different levels of particulate matter generated from different fuel sources in different geographical regions and countries affect different populations of people, especially those with underlying respiratory and cardiovascular conditions.
    
    “Whilst our findings show that targeting airway smooth muscle contraction or oxidative stress pathways may provide novel strategies for the protecting against the effects of landscape fire inhalation on respiratory and cardiovascular disease, more studies are required to identify appropriate therapies” says Professor Horvat.
    
    The research was conducted in collaboration with the Asthma and Breathing research program led by Professor Peter Gibson and Professor Vanessa McDonald, and National Heart Foundation Future Leader Fellow from the HMRI Heart and Stroke program, Professor Doan Ngo.
        </p>`
    },
    {
        id: 5,
        title: "Partnering to prevent local extinction of threatened marsupial",
        short: `The marsupial is at risk of local extinction due to habitat loss, damage and fragmentation, while also contending with heat stress, vehicle collisions and predation by introduced species.`,
        date: `3 Feb, 2024`,
        type: 'press release',
        slug: "partnering-to-prevent-local-extinction-of-threatened-marsupial",
        body: `<p className=" text-slate-700 leading-relaxed tracking-wider">
        A research team has developed a world-first platform to define the impact of exposure to landscape fire smoke on the heart and lungs.
        <br />
    
    The University of Newcastle and HMRI team, led by Professor Jay Horvat and Dr Henry Gomez, found short and long-term exposure to landscape fire smoke particulate matter (bushfire smoke) increased the hyperresponsiveness of airways and induced steroid-insensitivity in experimental asthma.
    
    They also found that short-term exposure to bushfire smoke decreased cardiac function and this was associated with the expression of gene changes relating to oxidative stress and cardiovascular pathologies.
    
    The research, driven by the events of the 2019 and 2020 ‘Black Summer’ bushfires, was funded by a Medical Research Future Fund grant.
    
    Professor Horvat said millions of people in Australia were exposed to unprecedented levels of particulate matter from landscape fires during the ‘Black Summer’ bushfires.
    
    “This was associated with large increases in people having respiratory and cardiovascular symptoms. People with asthma experienced worsened disease symptoms and had an increased needed to seek medical help as a result of exposure to particulate matter generated by the fires. Furthermore, the number heart attacks almost doubled in regional locations during the 2019/2020 Black Summer period.”
    
    The findings, published in The Journal of Allergy and Clinical Immunology, describe a world-first platform for understanding how landscape fire exposure affects heart and lung physiology. The research will be used to help identify therapies to protect people from the harmful effects of exposure.
    
    “Our research demonstrates that even small amounts of physiologically-relevant particular matter from landscape fire smoke has significant effects on lung and heart physiology, worsening key features of asthma and preventing mainstay suppressant medications from having much of an effect on symptoms,” says Professor Horvat.
    
    “What our experience showed us during the Black Summer bushfires is that completely avoiding exposure to landscape fire particulate matter inhalation is almost impossible. Our research shows that exposure to even low amounts of landscape fire particulate matter over a short period of time has a significant effect on heart and lung function.
    
    “Therefore, new therapeutic strategies are required to protect people from the harmful effects of exposure, particularly for those that are at increased risk, such as those with asthma or cardiovascular disease. Better strategies for treating and preventing the harmful effects of landscape fire smoke exposure are going to become more important given that the prevalence and intensity of landscape fires is likely to increase globally as a result of climate change.
    
    “Our findings show that particulate matter generated from different fuel sources have very similar effects at the same level of exposure. However, more research is required to determine how different levels of particulate matter generated from different fuel sources in different geographical regions and countries affect different populations of people, especially those with underlying respiratory and cardiovascular conditions.
    
    “Whilst our findings show that targeting airway smooth muscle contraction or oxidative stress pathways may provide novel strategies for the protecting against the effects of landscape fire inhalation on respiratory and cardiovascular disease, more studies are required to identify appropriate therapies” says Professor Horvat.
    
    The research was conducted in collaboration with the Asthma and Breathing research program led by Professor Peter Gibson and Professor Vanessa McDonald, and National Heart Foundation Future Leader Fellow from the HMRI Heart and Stroke program, Professor Doan Ngo.
        </p>`
    }
];

// TEMP: get this footer data from backend
// const data = [
//     { 
//         id: 1, 
//         header_title: 'Faculties & Centres', 
//         links: [
//             { 
//                 link_id: 1,
//                 link_text: 'Faculty of agriculture, fisheries & forestry', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 2,
//                 link_text: 'Faculty of Business & Tourism Studies', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 3,
//                 link_text: 'Faculty of Education & Humanities', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 4,
//                 link_text: 'Faculty of Nursing, Medicine & Health Sciences', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 5,
//                 link_text: 'Faculty of Science & Technology', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 6,
//                 link_text: 'University Prepatory College', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 7,
//                 link_text: 'Distance & Flexible Learning Centre', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 8,
//                 link_text: 'Centre for Productivity, Professional Development and Life-long Learning', 
//                 link_url: '#' 
//             },
//         ]
//     },
//     { 
//         id: 101, 
//         header_title: 'On our site', 
//         links: [
//             { 
//                 link_id: 102,
//                 link_text: 'latest news', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 103,
//                 link_text: 'Who we are', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 104,
//                 link_text: 'find a course', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 105,
//                 link_text: 'events', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 106,
//                 link_text: 'sitemap', 
//                 link_url: '#' 
//             },

//         ]
//     },
//     { 
//         id: 201, 
//         header_title: 'Popular Links', 
//         links: [
//             { 
//                 link_id: 202,
//                 link_text: 'e-learn', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 203,
//                 link_text: 'staff webmail', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 204,
//                 link_text: 'student webmail', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 205,
//                 link_text: 'jobs @ sinu', 
//                 link_url: '#' 
//             },
//             { 
//                 link_id: 206,
//                 link_text: 'sitemap', 
//                 link_url: '#' 
//             },

//         ]
//     }
// ]

export { DUMMY_NEWS };