name: Build and push images to GitHub Container Registry

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build images
    - name: Build app images - frontend and backend
      run: |
        docker build ./sinuweb_hdl_cms -t ghcr.io/solomon-islands-national-university/website-wagtailbackend:latest
        docker build  ./sinuweb-frontend -t ghcr.io/solomon-islands-national-university/website-nextjs:latest

    # Login to ghcr.io
    - name: Log in to GitHub Container Registry (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    # push images to ghcr.io
    - name: Push images to ghcr.io
      run: |
        docker push ghcr.io/solomon-islands-national-university/website-wagtailbackend:latest
        docker push ghcr.io/solomon-islands-national-university/website-nextjs:latest