name: Build and publish images to ghcr.io
on:
  push:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    # Create and use custom Builder
    - name: Create and use custom Buildx builder
      run: |
        docker buildx create --name cusbuilder --driver-opt network=sinuweb-net --use
        docker buildx inspect --bootstrap

    # Build images
    - name: Build images
      run: |
        docker network create -d bridge sinuweb-net
        docker compose -f compose.prod.yml up backend --build -d        
        docker compose -f compose.prod.yml up frontend --build -d
        docker compose -f compose.prod.yml up nginx -d


    # Login to ghcr.io
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    # push images to ghcr.io
    - name: publish images
      run: |
        docker push ghcr.io/solomon-islands-national-university/website-wagtailbackend:latest
        docker push ghcr.io/solomon-islands-national-university/website-nextjsfrontend:latest
