name: Build and publish images to ghcr.io
on:
  push:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build images
    - name: Build images
      run: |
        docker build ./sinuweb_hdl_cms -t ghcr.io/solomon-islands-national-university/website-wagtailbackend:latest
        docker build -f ./sinuweb-frontend/.docker/prod/Dockerfile ./sinuweb-frontend -t ghcr.io/solomon-islands-national-university/website-nextjsfrontend:latest

    # Login to ghcr.io
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    # push images to ghcr.io
    - name: publish images
      run: |
        docker push ghcr.io/solomon-islands-national-university/website-wagtailbackend:latest
        docker push ghcr.io/solomon-islands-national-university/website-nextjsfrontend:latest